from django.urls import path
from . import views
urlpatterns = [
    path('', views.titlescreen, name="moviemon/"),
    path('worldmap/', views.worldmap, name="moviemon/worldmap"),
    path('battle/', views.battle, name="moviemon/battle"),
    path('battle/1', views.battle, name="moviemon/battle/1"),
    path('battle/2', views.battle, name="moviemon/battle/2"),
    path('battle/3', views.battle, name="moviemon/battle/3"),
    path('battle/4', views.battle, name="moviemon/battle/4"),
    path('battle/5', views.battle, name="moviemon/battle/5"),
    path('battle/6', views.battle, name="moviemon/battle/6"),
    path('battle/6', views.battle, name="moviemon/battle/6"),
    path('battle/7', views.battle, name="moviemon/battle/7"),
    path('battle/8', views.battle, name="moviemon/battle/8"),
    path('battle/9', views.battle, name="moviemon/battle/9"),
    path('battle/10', views.battle, name="moviemon/battle/10"),
    path('load_game/', views.load_game, name="moviemon/load_game"),
    path('moviedex/', views.moviedex, name="moviemon/moviedex"),
    path('options/save_game', views.save, name="moviemon/options/save_game"),
    path('options/', views.options, name="moviemon/options"),
    path('detail/1', views.detail, name="moviemon/detail/1"),
    path('detail/2', views.detail, name="moviemon/detail/2"),
    path('detail/3', views.detail, name="moviemon/detail/3"),
    path('detail/4', views.detail, name="moviemon/detail/4"),
    path('detail/5', views.detail, name="moviemon/detail/5"),
    path('detail/6', views.detail, name="moviemon/detail/6"),
    path('detail/6', views.detail, name="moviemon/detail/6"),
    path('detail/7', views.detail, name="moviemon/detail/7"),
    path('detail/8', views.detail, name="moviemon/detail/8"),
    path('detail/9', views.detail, name="moviemon/detail/9"),
    path('detail/10', views.detail, name="moviemon/detail/10"),
    
]